### ISSUE TITLE
Containerize simulator (Docker)

### ISSUE THREAD

**Issue by alexliu22** [alexliu22/linkages#2]
We need to have a universal setup of the whole application for development & deployment across platforms.
This can be achieved with Docker containers. 
Research on docker, dockerfiles, dependencies, etc. needed.

**Comment by FranklinMao** [comment]
Helpful links:
https://docker-curriculum.com/

- Look through this and try out a local docker deploy.
- Cloud/AWS stuff not necessary right now.

**Comment by gabriel-wu2** [comment]
No longer needed
