### ISSUE TITLE
Create UI for different operations (buttons for each key press)

### ISSUE THREAD

**Issue by alexliu22** [alexliu22/linkages#5]
Currently, the tool uses keyboard input prompts to facilitate user interaction.
Figure out how to map these inputs to a UI.

**Comment by gabriel-wu2** [comment]
buttons in PyQt5
https://pythonspot.com/pyqt5-buttons/

An example of OpenGL and PyQt working together
https://www.youtube.com/watch?v=eJveTXSXs8Q&ab_channel=TrevorPayne

**Comment by alexliu22** [comment]
wxPython code example:
https://github.com/totex/wxPython-and-PyOpenGL/blob/master/mainApp.py
