### ISSUE TITLE
Add ability to drag joints

### ISSUE THREAD

**Issue by gabriel-wu2** [alexliu22/linkages#6]
Currently, the only way to move joints is to select the joint and select a position on the canvas that you want to move the joint to. We want to add the ability to click and hold a joint and move it around by dragging it.

**Comment by harishrajanala** [comment]
two ways to create better drag drop:
1. turn the linkage class into a component with vertex and edge components which can then become draggable
2. overlay a linkage component on top of the "drawing" on the canvas and mimic dragging between the two
