### ISSUE TITLE
Create toggle for the degrees of freedom lines of free joints

### ISSUE THREAD

**Issue by alexliu22** [alexliu22/linkages#7]

**Comment by gabriel-wu2** [comment]
Lines coming out of each joint represent the degrees of freedom of that joint. When certain orientations of joints exist and are moved, these lines can flicker and become confusing. 

Acceptance criteria: Add a UI component that allows this feature to be turned on/off

**Comment by gabriel-wu2** [comment]
The 'v' key toggles different views including one that does not show degrees of freedom. This ticket only entails turning that function into a more readily available UI.
